# This workflow will install Python dependencies, and run updates
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
  - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update
      run: |
        python src/extract_covid_data_br.py
    - name: Add & Commit
      uses: EndBug/add-and-commit@v5.0.0
      with:
        # Arguments for the git add command
        add: covid-br-ms-*.csv
        # The name of the user that will be displayed as the author of the commit
        #author_name: # optional
        # The email of the user that will be displayed as the author of the commit
        #author_email: # optional
        # Name of the branch to use, if different from the one that triggered the workflow
        #branch: # optional
        # The directory where your repository is located. You should use actions/checkout first to set it up
        #cwd: # optional, default is .
        # The message for the commit
        message: updating data
        # Arguments for the git rm command
        #remove: # optional
        # Whether to use the --signoff option on git commit
        #signoff: # optional
        # Arguments for the git tag command (the tag name always needs to be the first word not preceded by a hyphen)
        #tag: # optional
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
