# This workflow will install Python dependencies, and run updates
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
  - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update
      run: |
        python src/extract_covid_data_br.py
