# This workflow will install Python dependencies, and run updates
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update MS data

on:
  schedule:
  - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update
      run: |
        python src/extract_covid_data_br.py && date > last_update
    - name: Add & Commit
      uses: EndBug/add-and-commit@v5.0.0
      with:
        add: covid-br-ms-*.csv last_update
        message: updating data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
